modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "astral"
version = "${version}"
displayName = "Astral Armoury"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.astral]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.astral]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.astral]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
